const products = [
    {
        '_id': '1',
        'name': 'Xiaomi Redmi Airdots Bluetooth 5.0 Fones de ouvido sem fio',
        'image': '/images/fone-semfio-xiaomi.jpg',
        'description': 'Redmi AirDots é um verdadeiro fone de ouvido sem fio, o que significa que a conexão entre os fones de ouvido esquerdo e direito desaparece, mas a experiênciaEle ainda é simples. Ele vem com tecnologia Bluetooth 5.0 e segundos rápidos, você apenas traz seus fones de ouvido, AirDots está pronto, comece seu desempenho agora.',
        'brand': 'Xiaomi',
        'category': 'Electronics',
        'price': '199',
        'countInStock': '8',
        'rating': 3.5 ,
        'numReviews': 14 ,  
    },
    {
        '_id': '2',
        'name': 'Fone De Ouvido jbl Tune 115TWS Intra Auricular - com Microfone - Bluetooth - T115TWS',
        'image': '/images/fone-semfio-jbl.jpg',
        'description': 'Envolva-se no seu mundo. Você pode ouvir as suas músicas e chamadas telefônicas sem se preocupar com os fios. Com o Dual Connect, você pode usar um ou os dois fones quando quiser. Suas músicas favoritas ficam ainda melhores com o som do jbl Pure Bass. Com até 21 horas de duração de bateria e ajuste confortável, sua música continua tocando durante o dia todo. ',
        'brand': 'Jbl',
        'category': 'Electronics',
        'price': '361.80',
        'countInStock': '20',
        'rating': 4.5 ,
        'numReviews': 45 ,  
    },
    {
        '_id': '3',
        'name': 'Smartphone Xiaomi Redmi Note 8 4RAM 64GB Tela 6.3 LTE Dual Preto',
        'image': '/images/celular-xiaomi-note.jpg',
        'description': 'Smartphone Xiaomi Redmi note 8 64GB 4GB RAM Azul Versión Global, Sistema operacional: MIUI 10 (Base no sistema operacional Android 9), RAM: 4GB ROM: 64GB, Tela 6.3',
        'brand': 'Xiaomi Redmi',
        'category': 'Electronics',
        'price': '1.229.99',
        'countInStock': '10',
        'rating': 4 ,
        'numReviews': 30 ,  
    },
    {
        '_id': '4',
        'name': 'Carregador Wireless Sem Fio Indução Samsung S20 S21 Original',
        'image': '/images/carregador-sem-fio.jpg',
        'description': '1 cabo de energia e o adaptador carregador de parede são vendidos separadamente. O carregamento rápido sem fio é compatível com o Galaxy Note 5 e Galaxy S6e + e modelos posteriores das séries Galaxy S e Galaxy Note.',
        'brand': 'Samsung',
        'category': 'Electronics',
        'price': '219.70',
        'countInStock': '6',
        'rating': 2.5 ,
        'numReviews': 41 ,  
    },
    {
        '_id': '5',
        'name': 'Câmera Digital Canon EOS Dslr 5d Mark IV Corpo 30.4mp, 4k, Wi-Fi',
        'image': '/images/camera-eos-5d.jpg',
        'description': 'Continuando o seu legado de câmeras poderosas, a Canon lançou a DSLR 5D Mark IV , que é uma excelente opção de fotografia ainda e uma máquina que grava vídeo em 4K. Este perito multimídia oferece um sensor full-frame CMOS recentemente desenvolvido 30.4MP emparelhado com o DIGIC 6+ processador de imagem, a fim de equilibrar detalhes finos e resolução com desempenho de pouca luz e sensibilidade. ',
        'brand': 'Canon',
        'category': 'Electronics',
        'price': '18.769.53',
        'countInStock': '0',
        'rating': 5.5 ,
        'numReviews': 39 ,  
    },
    {
        '_id': '6',
        'name': 'Notebook Samsung Book Intel Core I3-1115G4 4GB 1TB W10 FHD 15.6 Cinza Chumbo NP550XDA-KT1BR',
        'image': '/images/notebook-samsung.jpg',
        'description': 'Intel® Core™ i3-1115G4 Processor (3.0 GHz up to 4.10 GHz 6 MB L3 Cache), HD (High Definition) Audio Intel® UHD Graphics - Integrada',
        'brand': 'Samsung',
        'category': 'Electronics',
        'price': '2.696.99',
        'countInStock': '12',
        'rating': 3.5 ,
        'numReviews': 39 ,  
    },
    
]

export default products
